# coding: utf-8

"""
    Idomoo API



    OpenAPI spec version: 2.0
    Contact: dev.support@idomoo.com

"""


import pprint
import re

import six


class AccessibilityResponseTranscriptLinks(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'language': 'str',
        'url': 'str'
    }

    attribute_map = {
        'language': 'language',
        'url': 'url'
    }

    def __init__(self, language=None, url=None):
        """AccessibilityResponseTranscriptLinks - a model defined in Swagger"""

        self._language = None
        self._url = None
        self.discriminator = None

        self.language = language
        self.url = url

    @property
    def language(self):
        """Gets the language of this AccessibilityResponseTranscriptLinks.

        The language for the transcript.

        :return: The language of this AccessibilityResponseTranscriptLinks.
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this AccessibilityResponseTranscriptLinks.

        The language for the transcript.

        :param language: The language of this AccessibilityResponseTranscriptLinks.
        :type: str
        """
        if language is None:
            raise ValueError("Invalid value for `language`, must not be `None`")

        self._language = language

    @property
    def url(self):
        """Gets the url of this AccessibilityResponseTranscriptLinks.

        Link to the transcript file.

        :return: The url of this AccessibilityResponseTranscriptLinks.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this AccessibilityResponseTranscriptLinks.

        Link to the transcript file.

        :param url: The url of this AccessibilityResponseTranscriptLinks.
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccessibilityResponseTranscriptLinks):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
