# coding: utf-8

"""
    Idomoo API



    OpenAPI spec version: 2.0
    Contact: dev.support@idomoo.com

"""


import pprint
import re

import six

from idomoo.models.gif_output_response_links import GifOutputResponseLinks


class GifOutputResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gif_fps': 'float',
        'height': 'int',
        'start': 'float',
        'duration': 'float',
        'suffix': 'str',
        'cost': 'float',
        'links': 'GifOutputResponseLinks'
    }

    attribute_map = {
        'gif_fps': 'gif_fps',
        'height': 'height',
        'start': 'start',
        'duration': 'duration',
        'suffix': 'suffix',
        'cost': 'cost',
        'links': 'links'
    }

    def __init__(self, gif_fps=None, height=None, start=None, duration=None, suffix=None, cost=None, links=None):
        """GifOutputResponse - a model defined in Swagger"""

        self._gif_fps = None
        self._height = None
        self._start = None
        self._duration = None
        self._suffix = None
        self._cost = None
        self._links = None
        self.discriminator = None

        if gif_fps is not None:
            self.gif_fps = gif_fps
        self.height = height
        self.start = start
        if duration is not None:
            self.duration = duration
        if suffix is not None:
            self.suffix = suffix
        self.cost = cost
        self.links = links

    @property
    def gif_fps(self):
        """Gets the gif_fps of this GifOutputResponse.

        The frame rate of the GIF. Default is the Video frame rate.

        :return: The gif_fps of this GifOutputResponse.
        :rtype: float
        """
        return self._gif_fps

    @gif_fps.setter
    def gif_fps(self, gif_fps):
        """Sets the gif_fps of this GifOutputResponse.

        The frame rate of the GIF. Default is the Video frame rate.

        :param gif_fps: The gif_fps of this GifOutputResponse.
        :type: float
        """
        if gif_fps is not None and gif_fps > 30:
            raise ValueError("Invalid value for `gif_fps`, must be a value less than or equal to `30`")

        self._gif_fps = gif_fps

    @property
    def height(self):
        """Gets the height of this GifOutputResponse.

        Height of the media rendered, in pixels. The width was automatically calculated to keep the aspect ratio.

        :return: The height of this GifOutputResponse.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this GifOutputResponse.

        Height of the media rendered, in pixels. The width was automatically calculated to keep the aspect ratio.

        :param height: The height of this GifOutputResponse.
        :type: int
        """
        if height is None:
            raise ValueError("Invalid value for `height`, must not be `None`")

        self._height = height

    @property
    def start(self):
        """Gets the start of this GifOutputResponse.

        What second of the storyboard timeline to start the GIF.

        :return: The start of this GifOutputResponse.
        :rtype: float
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this GifOutputResponse.

        What second of the storyboard timeline to start the GIF.

        :param start: The start of this GifOutputResponse.
        :type: float
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")

        self._start = start

    @property
    def duration(self):
        """Gets the duration of this GifOutputResponse.

        Seconds for the duration of the GIF.

        :return: The duration of this GifOutputResponse.
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this GifOutputResponse.

        Seconds for the duration of the GIF.

        :param duration: The duration of this GifOutputResponse.
        :type: float
        """

        self._duration = duration

    @property
    def suffix(self):
        """Gets the suffix of this GifOutputResponse.

        The suffix to the file name, if requested.

        :return: The suffix of this GifOutputResponse.
        :rtype: str
        """
        return self._suffix

    @suffix.setter
    def suffix(self, suffix):
        """Sets the suffix of this GifOutputResponse.

        The suffix to the file name, if requested.

        :param suffix: The suffix of this GifOutputResponse.
        :type: str
        """

        self._suffix = suffix

    @property
    def cost(self):
        """Gets the cost of this GifOutputResponse.

        Cost of the render in credits. A credit is 30 seconds or less.  GIFs don't cost if created from the video.

        :return: The cost of this GifOutputResponse.
        :rtype: float
        """
        return self._cost

    @cost.setter
    def cost(self, cost):
        """Sets the cost of this GifOutputResponse.

        Cost of the render in credits. A credit is 30 seconds or less.  GIFs don't cost if created from the video.

        :param cost: The cost of this GifOutputResponse.
        :type: float
        """
        if cost is None:
            raise ValueError("Invalid value for `cost`, must not be `None`")

        self._cost = cost

    @property
    def links(self):
        """Gets the links of this GifOutputResponse.


        :return: The links of this GifOutputResponse.
        :rtype: GifOutputResponseLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this GifOutputResponse.


        :param links: The links of this GifOutputResponse.
        :type: GifOutputResponseLinks
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GifOutputResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
