# coding: utf-8

"""
    Idomoo API



    OpenAPI spec version: 2.0
    Contact: dev.support@idomoo.com

"""


import pprint

import six

from idomoo.models.library_metadata import LibraryMetadata


class LibrariesList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'item_count': 'int',
        'libraries': 'list[LibraryMetadata]'
    }

    attribute_map = {
        'item_count': 'item_count',
        'libraries': 'libraries'
    }

    def __init__(self, item_count=None, libraries=None):
        """LibrariesList - a model defined in Swagger"""

        self._item_count = None
        self._libraries = None
        self.discriminator = None

        if item_count is not None:
            self.item_count = item_count
        if libraries is not None:
            self.libraries = libraries

    @property
    def item_count(self):
        """Gets the item_count of this LibrariesList.


        :return: The item_count of this LibrariesList.
        :rtype: int
        """
        return self._item_count

    @item_count.setter
    def item_count(self, item_count):
        """Sets the item_count of this LibrariesList.


        :param item_count: The item_count of this LibrariesList.
        :type: int
        """

        self._item_count = item_count

    @property
    def libraries(self):
        """Gets the libraries of this LibrariesList.


        :return: The libraries of this LibrariesList.
        :rtype: list[LibraryMetadata]
        """
        return self._libraries

    @libraries.setter
    def libraries(self, libraries):
        """Sets the libraries of this LibrariesList.


        :param libraries: The libraries of this LibrariesList.
        :type: list[LibraryMetadata]
        """

        self._libraries = libraries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LibrariesList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
