# coding: utf-8

"""
    Idomoo API



    OpenAPI spec version: 2.0
    Contact: dev.support@idomoo.com

"""


import pprint

import six


class SceneMetadataAudio(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'val': 'str',
        'start_time': 'float'
    }

    attribute_map = {
        'key': 'key',
        'val': 'val',
        'start_time': 'start_time'
    }

    def __init__(self, key=None, val=None, start_time=None):
        """SceneMetadataAudio - a model defined in Swagger"""

        self._key = None
        self._val = None
        self._start_time = None
        self.discriminator = None

        if key is not None:
            self.key = key
        if val is not None:
            self.val = val
        if start_time is not None:
            self.start_time = start_time

    @property
    def key(self):
        """Gets the key of this SceneMetadataAudio.


        :return: The key of this SceneMetadataAudio.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this SceneMetadataAudio.


        :param key: The key of this SceneMetadataAudio.
        :type: str
        """

        self._key = key

    @property
    def val(self):
        """Gets the val of this SceneMetadataAudio.


        :return: The val of this SceneMetadataAudio.
        :rtype: str
        """
        return self._val

    @val.setter
    def val(self, val):
        """Sets the val of this SceneMetadataAudio.


        :param val: The val of this SceneMetadataAudio.
        :type: str
        """

        self._val = val

    @property
    def start_time(self):
        """Gets the start_time of this SceneMetadataAudio.


        :return: The start_time of this SceneMetadataAudio.
        :rtype: float
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this SceneMetadataAudio.


        :param start_time: The start_time of this SceneMetadataAudio.
        :type: float
        """

        self._start_time = start_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SceneMetadataAudio):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
