# coding: utf-8

"""
    Idomoo API



    OpenAPI spec version: 2.0
    Contact: dev.support@idomoo.com

"""


import pprint

import six


class SceneMetadataMedia(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'val': 'str',
        'height': 'float',
        'width': 'float'
    }

    attribute_map = {
        'key': 'key',
        'val': 'val',
        'height': 'height',
        'width': 'width'
    }

    def __init__(self, key=None, val=None, height=None, width=None):
        """SceneMetadataMedia - a model defined in Swagger"""

        self._key = None
        self._val = None
        self._height = None
        self._width = None
        self.discriminator = None

        if key is not None:
            self.key = key
        if val is not None:
            self.val = val
        if height is not None:
            self.height = height
        if width is not None:
            self.width = width

    @property
    def key(self):
        """Gets the key of this SceneMetadataMedia.


        :return: The key of this SceneMetadataMedia.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this SceneMetadataMedia.


        :param key: The key of this SceneMetadataMedia.
        :type: str
        """

        self._key = key

    @property
    def val(self):
        """Gets the val of this SceneMetadataMedia.


        :return: The val of this SceneMetadataMedia.
        :rtype: str
        """
        return self._val

    @val.setter
    def val(self, val):
        """Sets the val of this SceneMetadataMedia.


        :param val: The val of this SceneMetadataMedia.
        :type: str
        """

        self._val = val

    @property
    def height(self):
        """Gets the height of this SceneMetadataMedia.


        :return: The height of this SceneMetadataMedia.
        :rtype: float
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this SceneMetadataMedia.


        :param height: The height of this SceneMetadataMedia.
        :type: float
        """

        self._height = height

    @property
    def width(self):
        """Gets the width of this SceneMetadataMedia.


        :return: The width of this SceneMetadataMedia.
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this SceneMetadataMedia.


        :param width: The width of this SceneMetadataMedia.
        :type: float
        """

        self._width = width

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SceneMetadataMedia):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
