# coding: utf-8

"""
    Idomoo API



    OpenAPI spec version: 2.0
    Contact: dev.support@idomoo.com

"""


import pprint
import re

import six


class StoryboardMetadataData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'val': 'str',
        'type': 'str',
        'description': 'str'
    }

    attribute_map = {
        'key': 'key',
        'val': 'val',
        'type': 'type',
        'description': 'description'
    }

    def __init__(self, key=None, val=None, type=None, description=None):
        """StoryboardMetadataData - a model defined in Swagger"""

        self._key = None
        self._val = None
        self._type = None
        self._description = None
        self.discriminator = None

        if key is not None:
            self.key = key
        if val is not None:
            self.val = val
        if type is not None:
            self.type = type
        if description is not None:
            self.description = description

    @property
    def key(self):
        """Gets the key of this StoryboardMetadataData.


        :return: The key of this StoryboardMetadataData.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this StoryboardMetadataData.


        :param key: The key of this StoryboardMetadataData.
        :type: str
        """

        self._key = key

    @property
    def val(self):
        """Gets the val of this StoryboardMetadataData.


        :return: The val of this StoryboardMetadataData.
        :rtype: str
        """
        return self._val

    @val.setter
    def val(self, val):
        """Sets the val of this StoryboardMetadataData.


        :param val: The val of this StoryboardMetadataData.
        :type: str
        """

        self._val = val

    @property
    def type(self):
        """Gets the type of this StoryboardMetadataData.


        :return: The type of this StoryboardMetadataData.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this StoryboardMetadataData.


        :param type: The type of this StoryboardMetadataData.
        :type: str
        """

        self._type = type

    @property
    def description(self):
        """Gets the description of this StoryboardMetadataData.


        :return: The description of this StoryboardMetadataData.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this StoryboardMetadataData.


        :param description: The description of this StoryboardMetadataData.
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StoryboardMetadataData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
