# coding: utf-8

"""
    Idomoo API



    OpenAPI spec version: 2.0
    Contact: dev.support@idomoo.com

"""


import pprint
import re

import six

from idomoo.models.video_output_response_links import VideoOutputResponseLinks


class VideoOutputResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'video_type': 'str',
        'quality': 'int',
        'height': 'int',
        'suffix': 'str',
        'duration': 'float',
        'cost': 'float',
        'links': 'VideoOutputResponseLinks'
    }

    attribute_map = {
        'video_type': 'video_type',
        'quality': 'Quality',
        'height': 'height',
        'suffix': 'suffix',
        'duration': 'duration',
        'cost': 'cost',
        'links': 'links'
    }

    def __init__(self, video_type=None, quality=None, height=None, suffix=None, duration=None, cost=None, links=None):
        """VideoOutputResponse - a model defined in Swagger"""

        self._video_type = None
        self._quality = None
        self._height = None
        self._suffix = None
        self._duration = None
        self._cost = None
        self._links = None
        self.discriminator = None

        self.video_type = video_type
        if quality is not None:
            self.quality = quality
        self.height = height
        if suffix is not None:
            self.suffix = suffix
        self.duration = duration
        self.cost = cost
        self.links = links

    @property
    def video_type(self):
        """Gets the video_type of this VideoOutputResponse.

        Type of x264 to output returned. HLS or MP4.

        :return: The video_type of this VideoOutputResponse.
        :rtype: str
        """
        return self._video_type

    @video_type.setter
    def video_type(self, video_type):
        """Sets the video_type of this VideoOutputResponse.

        Type of x264 to output returned. HLS or MP4.

        :param video_type: The video_type of this VideoOutputResponse.
        :type: str
        """
        if video_type is None:
            raise ValueError("Invalid value for `video_type`, must not be `None`")
        allowed_values = ["mp4", "hls"]
        if video_type not in allowed_values:
            raise ValueError(
                "Invalid value for `video_type` ({0}), must be one of {1}"
                .format(video_type, allowed_values)
            )

        self._video_type = video_type

    @property
    def quality(self):
        """Gets the quality of this VideoOutputResponse.

        Quality of x264. The lower the number, the higher the quality and file size.

        :return: The quality of this VideoOutputResponse.
        :rtype: int
        """
        return self._quality

    @quality.setter
    def quality(self, quality):
        """Sets the quality of this VideoOutputResponse.

        Quality of x264. The lower the number, the higher the quality and file size.

        :param quality: The quality of this VideoOutputResponse.
        :type: int
        """
        if quality is not None and quality > 50:
            raise ValueError("Invalid value for `quality`, must be a value less than or equal to `50`")
        if quality is not None and quality < 1:
            raise ValueError("Invalid value for `quality`, must be a value greater than or equal to `1`")

        self._quality = quality

    @property
    def height(self):
        """Gets the height of this VideoOutputResponse.

        Height of the media rendered, in pixels. The width was automatically calculated to keep the aspect ratio.

        :return: The height of this VideoOutputResponse.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this VideoOutputResponse.

        Height of the media rendered, in pixels. The width was automatically calculated to keep the aspect ratio.

        :param height: The height of this VideoOutputResponse.
        :type: int
        """
        if height is None:
            raise ValueError("Invalid value for `height`, must not be `None`")

        self._height = height

    @property
    def suffix(self):
        """Gets the suffix of this VideoOutputResponse.

        The suffix to the file name, if requested.

        :return: The suffix of this VideoOutputResponse.
        :rtype: str
        """
        return self._suffix

    @suffix.setter
    def suffix(self, suffix):
        """Sets the suffix of this VideoOutputResponse.

        The suffix to the file name, if requested.

        :param suffix: The suffix of this VideoOutputResponse.
        :type: str
        """

        self._suffix = suffix

    @property
    def duration(self):
        """Gets the duration of this VideoOutputResponse.

        The duration that was rendered in seconds.

        :return: The duration of this VideoOutputResponse.
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this VideoOutputResponse.

        The duration that was rendered in seconds.

        :param duration: The duration of this VideoOutputResponse.
        :type: float
        """
        if duration is None:
            raise ValueError("Invalid value for `duration`, must not be `None`")

        self._duration = duration

    @property
    def cost(self):
        """Gets the cost of this VideoOutputResponse.

        Cost of the render in credits. A credit is 30 seconds or less.

        :return: The cost of this VideoOutputResponse.
        :rtype: float
        """
        return self._cost

    @cost.setter
    def cost(self, cost):
        """Sets the cost of this VideoOutputResponse.

        Cost of the render in credits. A credit is 30 seconds or less.

        :param cost: The cost of this VideoOutputResponse.
        :type: float
        """
        if cost is None:
            raise ValueError("Invalid value for `cost`, must not be `None`")

        self._cost = cost

    @property
    def links(self):
        """Gets the links of this VideoOutputResponse.


        :return: The links of this VideoOutputResponse.
        :rtype: VideoOutputResponseLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this VideoOutputResponse.


        :param links: The links of this VideoOutputResponse.
        :type: VideoOutputResponseLinks
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VideoOutputResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
