# coding: utf-8

"""
    Idomoo API



    OpenAPI spec version: 2.0
    Contact: dev.support@idomoo.com

"""


import pprint

import six


class VideoOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'video_type': 'str',
        'quality': 'int',
        'height': 'int',
        'suffix': 'str',
        'overlay': 'str',
        'overlay_alignment': 'list[str]',
        'overlay_scale': 'str',
        'landing_page_id': 'str',
        'label': 'str'
    }

    attribute_map = {
        'video_type': 'video_type',
        'quality': 'quality',
        'height': 'height',
        'suffix': 'suffix',
        'overlay': 'overlay',
        'overlay_alignment': 'overlay_alignment',
        'overlay_scale': 'overlay_scale',
        'landing_page_id': 'landing_page_id',
        'label': 'label'
    }

    def __init__(self, video_type=None, quality=None, height=None, suffix=None, overlay=None, overlay_alignment=None,
                 overlay_scale='fit', landing_page_id=None, label=None):
        """VideoOutput - a model defined in Swagger"""

        self._video_type = None
        self._quality = None
        self._height = None
        self._suffix = None
        self._overlay = None
        self._overlay_alignment = None
        self._overlay_scale = None
        self._landing_page_id = None
        self._label = None
        self.discriminator = None

        self.video_type = video_type
        if quality is not None:
            self.quality = quality
        self.height = height
        if suffix is not None:
            self.suffix = suffix
        if overlay is not None:
            self.overlay = overlay
        if overlay_alignment is not None:
            self.overlay_alignment = overlay_alignment
        if overlay_scale is not None:
            self.overlay_scale = overlay_scale
        if landing_page_id is not None:
            self.landing_page_id = landing_page_id
        if label is not None:
            self.label = label

    @property
    def video_type(self):
        """Gets the video_type of this VideoOutput.

        Type of x264 to output. Render HLS for real-time playback and MP4 if you just need a file.

        :return: The video_type of this VideoOutput.
        :rtype: str
        """
        return self._video_type

    @video_type.setter
    def video_type(self, video_type):
        """Sets the video_type of this VideoOutput.

        Type of x264 to output. Render HLS for real-time playback and MP4 if you just need a file.

        :param video_type: The video_type of this VideoOutput.
        :type: str
        """
        if video_type is None:
            raise ValueError("Invalid value for `video_type`, must not be `None`")
        allowed_values = ["mp4", "hls"]
        if video_type not in allowed_values:
            raise ValueError(
                "Invalid value for `video_type` ({0}), must be one of {1}"
                .format(video_type, allowed_values)
            )

        self._video_type = video_type

    @property
    def quality(self):
        """Gets the quality of this VideoOutput.

        Quality of x264. The lower the number, the higher the quality and file size. Numbers between 21 - 29 should
        be more than enough for most uses.

        :return: The quality of this VideoOutput.
        :rtype: int
        """
        return self._quality

    @quality.setter
    def quality(self, quality):
        """Sets the quality of this VideoOutput.

        Quality of x264. The lower the number, the higher the quality and file size. Numbers between 21 - 29 should
        be more than enough for most uses.

        :param quality: The quality of this VideoOutput.
        :type: int
        """
        if quality is not None and quality > 50:
            raise ValueError("Invalid value for `quality`, must be a value less than or equal to `50`")
        if quality is not None and quality < 1:
            raise ValueError("Invalid value for `quality`, must be a value greater than or equal to `1`")

        self._quality = quality

    @property
    def height(self):
        """Gets the height of this VideoOutput.

        Height of the media to be rendered, in pixels. Should be the height of your scenes unless a smaller
        resolution is needed. Resolution higher than the scene resolution reduces quality. The width is automatically
        calculated to keep the aspect ratio.

        :return: The height of this VideoOutput.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this VideoOutput.

        Height of the media to be rendered, in pixels. Should be the height of your scenes unless a smaller
        resolution is needed. Resolution higher than the scene resolution reduces quality. The width is automatically
        calculated to keep the aspect ratio.

        :param height: The height of this VideoOutput.
        :type: int
        """
        if height is None:
            raise ValueError("Invalid value for `height`, must not be `None`")

        self._height = height

    @property
    def suffix(self):
        """Gets the suffix of this VideoOutput.

        Unique ending of the file name so several outputs can be created then identified. Required if there is more
        then 1 video output.

        :return: The suffix of this VideoOutput.
        :rtype: str
        """
        return self._suffix

    @suffix.setter
    def suffix(self, suffix):
        """Sets the suffix of this VideoOutput.

        Unique ending of the file name so several outputs can be created then identified. Required if there is more
        then 1 video output.

        :param suffix: The suffix of this VideoOutput.
        :type: str
        """

        self._suffix = suffix

    @property
    def overlay(self):
        """Gets the overlay of this VideoOutput.

        Path to overlay image, such as: play button or watermark.

        :return: The overlay of this VideoOutput.
        :rtype: str
        """
        return self._overlay

    @overlay.setter
    def overlay(self, overlay):
        """Sets the overlay of this VideoOutput.

        Path to overlay image, such as: play button or watermark.

        :param overlay: The overlay of this VideoOutput.
        :type: str
        """

        self._overlay = overlay

    @property
    def overlay_alignment(self):
        """Gets the overlay_alignment of this VideoOutput.

        Alignment for overlay image in case the image doesn't fit the video perfectly. The first item in the array is
        X. The second is Y.

        :return: The overlay_alignment of this VideoOutput.
        :rtype: list[str]
        """
        return self._overlay_alignment

    @overlay_alignment.setter
    def overlay_alignment(self, overlay_alignment):
        """Sets the overlay_alignment of this VideoOutput.

        Alignment for overlay image in case the image doesn't fit the video perfectly. The first item in the array is
        X. The second is Y.

        :param overlay_alignment: The overlay_alignment of this VideoOutput.
        :type: list[str]
        """
        allowed_values = ["left", "center", "right", "top", "middle", "bottom"]
        if not set(overlay_alignment).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `overlay_alignment` [{0}], must be a subset of [{1}]"
                .format(", ".join(map(str, set(overlay_alignment) - set(allowed_values))),
                        ", ".join(map(str, allowed_values)))
            )

        self._overlay_alignment = overlay_alignment

    @property
    def overlay_scale(self):
        """Gets the overlay_scale of this VideoOutput.

        Scale the overlay image if it's not the same size as the video. * Fit: scale the image up or down so it's
        completely visible in the video's resolution. If not the same aspect ratio, transparency is added around the
        image according to the alignment settings. * Fill: scale the image up or down so it completely fills the
        video. If not the same aspect ratio, the image is cropped according to the alignment settings.  * None: don't
        resize the overlay image.

        :return: The overlay_scale of this VideoOutput.
        :rtype: str
        """
        return self._overlay_scale

    @overlay_scale.setter
    def overlay_scale(self, overlay_scale):
        """Sets the overlay_scale of this VideoOutput.

        Scale the overlay image if it's not the same size as the video. * Fit: scale the image up or down so it's
        completely visible in the video's resolution. If not the same aspect ratio, transparency is added around the
        image according to the alignment settings. * Fill: scale the image up or down so it completely fills the
        video. If not the same aspect ratio, the image is cropped according to the alignment settings.  * None: don't
        resize the overlay image.

        :param overlay_scale: The overlay_scale of this VideoOutput.
        :type: str
        """
        allowed_values = ["fit", "fill", "none"]
        if overlay_scale not in allowed_values:
            raise ValueError(
                "Invalid value for `overlay_scale` ({0}), must be one of {1}"
                .format(overlay_scale, allowed_values)
            )

        self._overlay_scale = overlay_scale

    @property
    def landing_page_id(self):
        """Gets the landing_page_id of this VideoOutput.

        The ID of the landing page that is returned in the response to present the video in.

        :return: The landing_page_id of this VideoOutput.
        :rtype: str
        """
        return self._landing_page_id

    @landing_page_id.setter
    def landing_page_id(self, landing_page_id):
        """Sets the landing_page_id of this VideoOutput.

        The ID of the landing page that is returned in the response to present the video in.

        :param landing_page_id: The landing_page_id of this VideoOutput.
        :type: str
        """

        self._landing_page_id = landing_page_id

    @property
    def label(self):
        """Gets the label of this VideoOutput.

        This label is another way to identify this specific output. The label is returned in the response,
        but does not appear in the file name.

        :return: The label of this VideoOutput.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this VideoOutput.

        This label is another way to identify this specific output. The label is returned in the response,
        but does not appear in the file name.

        :param label: The label of this VideoOutput.
        :type: str
        """

        self._label = label

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VideoOutput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
